### ISSUE TITLE
t/03-import-context.t fails on cygwin/win7

### ISSUE THREAD

**Issue by devel-chm** [nrdvana/perl-X11-GLX#2]
Output from perl -V:

> Summary of my perl5 (revision 5 version 22 subversion 3) configuration:
>    
>   Platform:
>     osname=cygwin, osvers=2.6.1(0.30553), archname=cygwin-thread-multi
>     uname='cygwin_nt-6.3 cygwin 2.6.1(0.30553) 2016-12-16 11:55 x86_64 cygwin '
>     config_args='-des -Dprefix=/usr -Dmksymlinks -Darchname=x86_64-cygwin-threads -Dlibperl=cygperl5_22.dll -Dcc=gcc -Dld=g++ -Accflags=-ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.3-1 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-5.22.3=/usr/src/debug/perl-5.22.3-1 -fwrapv'
>     hint=recommended, useposix=true, d_sigaction=define
>     useithreads=define, usemultiplicity=define
>     use64bitint=define, use64bitall=define, uselongdouble=undef
>     usemymalloc=n, bincompat5005=undef
>   Compiler:
>     cc='gcc', ccflags ='-DPERL_USE_SAFE_PUTENV -D_GNU_SOURCE -U__STRICT_ANSI__ -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.3-1 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-5.22.3=/usr/src/debug/perl-5.22.3-1 -fwrapv -fno-strict-aliasing -fstack-protector-strong -D_FORTIFY_SOURCE=2',
>     optimize='-O3',
>     cppflags='-DPERL_USE_SAFE_PUTENV -D_GNU_SOURCE -U__STRICT_ANSI__ -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/build=/usr/src/debug/perl-5.22.3-1 -fdebug-prefix-map=/mnt/share/maint/perl.x86_64/src/perl-5.22.3=/usr/src/debug/perl-5.22.3-1 -fwrapv -fno-strict-aliasing -fstack-protector-strong'
>     ccversion='', gccversion='5.4.0', gccosandvers=''
>     intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678, doublekind=3
>     d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16, longdblkind=3
>     ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
>     alignbytes=8, prototype=define
>   Linker and Libraries:
>     ld='g++', ldflags =' -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'
>     libpth=/usr/lib
>     libs=-lpthread -lgdbm -ldb -ldl -lcrypt -lgdbm_compat
>     perllibs=-lpthread -ldl -lcrypt
>     libc=/usr/lib/libcygwin.a, so=dll, useshrplib=true, libperl=cygperl5_22.dll
>     gnulibc_version=''
>   Dynamic Linking:
>     dlsrc=dl_dlopen.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
>     cccdlflags=' ', lddlflags=' --shared  -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'
> 
> 
> Characteristics of this binary (from libperl): 
>   Compile-time options: HAS_TIMES MULTIPLICITY PERLIO_LAYERS
>                         PERL_DONT_CREATE_GVSV
>                         PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
>                         PERL_IMPLICIT_CONTEXT PERL_NEW_COPY_ON_WRITE
>                         PERL_PRESERVE_IVUV PERL_USE_SAFE_PUTENV
>                         USE_64_BIT_ALL USE_64_BIT_INT USE_ITHREADS
>                         USE_LARGE_FILES USE_LOCALE USE_LOCALE_COLLATE
>                         USE_LOCALE_CTYPE USE_LOCALE_NUMERIC USE_LOCALE_TIME
>                         USE_PERLIO USE_PERL_ATOF USE_REENTRANT_API
>   Built under cygwin
>   Compiled at Jan 15 2017 13:11:06
>   %ENV:
>     PERL5LIB="/home/chm/local64/lib/perl5"
>     PERLDOC_PAGER="less"
>   @INC:
>     /home/chm/local64/lib/perl5/cygwin-thread-multi
>     /home/chm/local64/lib/perl5
>     /usr/lib/perl5/site_perl/5.22/x86_64-cygwin-threads
>     /usr/lib/perl5/site_perl/5.22
>     /usr/lib/perl5/vendor_perl/5.22/x86_64-cygwin-threads
>     /usr/lib/perl5/vendor_perl/5.22
>     /usr/lib/perl5/5.22/x86_64-cygwin-threads
>     /usr/lib/perl5/5.22
>     .
> 

Output from uname -a:
> CYGWIN_NT-6.1 tesseract-4 2.6.1(0.305/5/3) 2016-12-16 11:55 x86_64 Cygwin

Output from test with failure:
>  perl -Mblib t/03-import-context.t 
> 1..11
> ok 1 - X11 connection
> ok 2 - glXQueryVersion
> ok 3 - returned version
> \# GLX Version 1.4
> ok 4 - glxQueryExtensionsString
> \# GLX Extensions: GLX_ARB_get_proc_address GLX_ARB_multisample GLX_EXT_import_context GLX_EXT_visual_info GLX_EXT_visual_rating GLX_MESA_copy_sub_buffer GLX_MESA_multithread_makecurrent GLX_MESA_swap_control GLX_OML_swap_method GLX_SGI_make_current_read GLX_SGIS_multisample GLX_SGIX_fbconfig GLX_SGIX_pbuffer GLX_SGIX_visual_select_group 
> ok 5 - glXChooseVisual
> ok 6 - glXCreateContext
> ok 7 - XCreatePixmap
> X Error of failed request:  BadValue (integer parameter out of range for operation)
>   Major opcode of failed request:  149 (GLX)
>   Minor opcode of failed request:  3 (X_GLXCreateContext)
>   Value in failed request:  0x0
>   Serial number of failed request:  826
>   Current serial number in output stream:  829
> 

Sorry I don't know enough about X11 and GLX to debug the problem.

**Comment by nrdvana** [comment]
As I just mentioned in the other ticket, I'm not sure why GLXCreateContext would fail.  It appears you have this function in your libGL, else the compile would fail, but for some reason it isn't available on your X server.

**Comment by nrdvana** [comment]
Oh wait!  I mis-read the error.  The failure is ```glXCreateContext($display, $visual, undef, 0)```, and it is probably complaining about the '0' being invalid.  In this case I'm asking for an indirect rendering context, and it might be that your server doesn't support that or has it disabled.  (and in fact, modern Linux distros do disable indirect rendering, though no clue about the status on cygwin)

I guess I'll need to guard the test case with something that identifies whether indirect contexts are supported/enabled.

**Comment by nrdvana** [comment]
If you remove this test case, do the rest pass?

**Comment by devel-chm** [comment]
Do you mean skip the entire t/03*.t or what?  I'm on #pogl on irc.perl.org if you wish to chat about this...

**Comment by devel-chm** [comment]
If I leave t/03*.t out then the remaining tests pass.

**Comment by nrdvana** [comment]
Can you test and see if this patch fixes it for you?  You'll also need the latest X11::Xlib, which I just pushed to CPAN as version 0.15.

**Comment by devel-chm** [comment]
BTW, I was reading the cygwin/X docs and apparently you can enable 
indirect contexts with some flags when you start the X server.  By default 
indirect contexts in GLX are not enabled.  If you like I can test with and
without indirect GLX contexts and let you know how it goes....

**Comment by nrdvana** [comment]
Sorry, I meant to push out the new version last weekend.  The commit above (4ff0407) should be a reasonable test for whether indirect is enabled, so the tests should pass in either server configuration now.

I've deployed to cpan as 0.03.  I also pushed an X11::Xlib 0.16 to correct a test failure on some CPAN Tester boxes, though if you got 0.15 installed, the module is the same.
